### ISSUE TITLE
Image path for map layout should be saved relative to the project path

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#30567]
**Feature description.**
When creating layouts in QGIS a user can add images to the layout and the path to this is an **absolute** URL to where the image comes from ie

![lyout](https://user-images.githubusercontent.com/2510900/60710797-c502c980-9f13-11e9-956c-6c21b64b9abd.png)

In the project file it is saved as  an **absolute** path
![patha](https://user-images.githubusercontent.com/2510900/60710950-1317cd00-9f14-11e9-9ff5-2c14fc84135a.png)

This presents a lot of problems when the QGIS Projects are used with QGIS Server  i.e  in docker

```
version: '2'
volumes:
  web-data: {}
services:
  
  web:
    image: 3liz/qgis-map-server:3.8
    environment:
      QGSRV_SERVER_WORKERS: 2
      QGSRV_LOGGING_LEVEL: 'DEBUG'
      QGSRV_CACHE_ROOTDIR: /projects
      QGSRV_CACHE_SIZE: 10
      QGSRV_SERVER_PLUGINPATH: /plugin
      QGIS_SERVER_PARALLEL_RENDERING: 'true'
      QGIS_SERVER_MAX_THREADS: 6
    ports:
    - 8080:8080
    volumes:
    - web-data:/projects
    - ./plugins:/plugin
```
If I mount the folder containing the project file and do a print request using the print layout the images are not found as I would have to edit the QGIS project to change the path
