### ISSUE TITLE
QGIS Server: WMS does not notice changes of QGIS Project in PostGIS, but WFS does

### ISSUE THREAD

**Issue by JakobMiksch** [qgis/QGIS#56622]
### What is the bug or the crash?

When running QGIS Server with `QGIS_SERVER_PROJECT_CACHE_STRATEGY=periodic` (see [docs](QGIS_SERVER_PROJECT_CACHE_STRATEGY)), QGIS Server should react on changes of the QGIS project. This works well for WFS but **not for WMS**. 

### Steps to reproduce the issue

- start QGIS Server 3.36 with this settings (Docker compose file as example)

```
version: '3.8'
services:
  qgis_server:
    image: camptocamp/qgis-server:3.36
    volumes:
      - ./pg_service.conf:/home/.pg_service.conf
    environment:
      - QGIS_SERVER_PROJECT_CACHE_STRATEGY=periodic
      - PGSERVICEFILE=/home/.pg_service.conf
    ports:
      - "8082:80"
```

- create a QGIS project with a vector layer named `alpha` and ensure it is published both as WMS and WFS
- store this project in PostGIS
- Make a WMS and a WFS capabilities  request to the project in the database and remember the response
  - both responses should list the layer `alpha` in their response
- change the the name of the layer in your QGIS project from `alpha` to `beta`  and save the project
- Request the WMS and the WFS capabilities again. Result: 
  - WFS contains the layer called `beta` in its response
  - WMS still contains `alpha` in its response 

### Versions

3.36

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)
